# hosts.yml
---
all:
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
  hosts:
    hydrogen:
      ansible_host: 192.168.23.11
    helium:
      ansible_host: 192.168.23.12
    lithium:
      ansible_host: 192.168.23.13