---
- name: Examples of tag usage
  hosts: all
  gather_facts: no

  tasks:
    - name: task-1
      ansible.builtin.debug:
    - name: task-2
      ansible.builtin.import_role: 
        name: test_role
      tags: job1
    - name: task-3
      ansible.builtin.debug:
