- name: Example of "ansible.builtin.import_tasks" usage
  hosts: all
  gather_facts: no

  tasks:
    - name: Message No.1
      ansible.builtin.debug:
    
    - name: import tasks
      ansible.builtin.import_tasks: ./imports/imp_task4.yml
      become: yes

    - name: Message No.2
      ansible.builtin.debug:
