---
# group_vars/zabbix_group.yml
# ・ Zabbix サーバーのデプロイに使用する変数

# -------------------- MySQL --------------------
# root アカウントのパスワード
mysql_root_pass: "MS-05B@Zeonic"

# レポジトリの URL
mysql_repo_url : "https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm"

# 必要なパッケージ
mysql_packages:
  - mysql-community-server
  - python3-PyMySQL

# サービス名
mysql_srv_name: "mysqld.service"

# -------------------- Zabbix --------------------
# Zabbix 用に MySql に作成するデータベース名
zabbix_db_name: "zabbix_db"

# Zabbix 用に MySql に作成するユーザー名とパスワード
zabbix_user: "zabbixuser"
zabbix_pass: "MSM-07@Mip"

# レポジトリの URL
zabbix_repo_url : "https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm"

# 必要なパッケージ
zabbix_packages:
  - httpd
  - php
  - zabbix-server-mysql
  - zabbix-web-japanese
  - zabbix-apache-conf
  - zabbix-agent2

# ファイアウォールに穴を開けるポート
zabbix_ports:
  - 10051/tcp              # Zabbix agent
  - 80/tcp                 # Apache (http)

# サービス名
zabbix_services:
  - httpd.service
  - php-fpm.service
  - zabbix-server.service
  - zabbix-agent2.service
