- name: Example of "ansible.builtin.include_tasks" usage
  hosts: all
  gather_facts: no

  tasks:
    - name: Message No.1
      ansible.builtin.debug:
    
    - name: include tasks
      ansible.builtin.include_tasks: ./includes/inc_task5.yml
      tags: job1

    - name: Message No.2
      ansible.builtin.debug:
