---
- name: Apache server installed
  hosts: web
  become: yes

  tasks:
  - name: Install Apache
    ansible.builtin.dnf:
      name: httpd
      state: present
  - name: Apache enabled and running
    ansible.builtin.systemd:
      name: httpd.service
      state: started
      enabled: yes
  - name: copy index.html
    ansible.builtin.template:
      src: ./index.j2
      dest: /var/www/html/index.html
      mode: '0644'
