---
- name: Example of using roles
  hosts: all

  tasks:
    - name: The ansible.builtin.import_role module with the loop directive set
      ansible.builtin.import_role:
        name: loop-test
      loop:
        - 1
        - 2
        - 3
