---
all:
  hosts:
    hydrogen:
      ansible_host: 192.168.23.11
      ansible_user: ansible-user
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    webservers:
      hosts:
        helium:
          ansible_host: 192.168.23.12
          ansible_user: ansible-user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          http_port: 8080
        lithium:
          ansible_host: 192.168.23.13
          ansible_user: ansible-user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          http_port: 8080
    dbservers:
      hosts:
        lithium:
