---
all:
  hosts:
    hydrogen:
      ansible_host: 192.168.23.11
      ansible_user: ansible-user
      ansible_password: fo&Ebr=3hucrlpeclspE
    helium:
      ansible_host: 192.168.23.12
      ansible_user: ansible-user
      ansible_password: fo&Ebr=3hucrlpeclspE
    lithium:
      ansible_host: 192.168.23.13
      ansible_user: ansible-user
      ansible_password: fo&Ebr=3hucrlpeclspE
