---
all:
  vars:
    locate_timezone: Asia/Tokyo
  hosts:
    hydrogen:
      ansible_host: 192.168.23.11
      ansible_user: ansible-user
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    webservers:
      vars:
        http_port: 8080
      hosts:
        helium:
          ansible_host: 192.168.23.12
          ansible_user: ansible-user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        lithium:
          ansible_host: 192.168.23.13
          ansible_user: ansible-user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    dbservers:
      vars:
        db_user: scott
        db_pass: tiger
        db_port: 1521
      hosts:
        lithium:
