---
- name: Example of error handling usage
  hosts: all

  tasks:
    - name: Use with loop directive
      ansible.builtin.debug:
        msg: "loop The value of the variable -> {{ item }}"
      loop:
        - 1
        - 2
        - 3
      register: result_of_loop

    - name: Display the contents of register variables
      ansible.builtin.debug:
        var: result_of_loop
