---
- name: Example of error handling usage
  hosts: all
  gather_facts: no

  tasks:
    - name: First processing
      ansible.builtin.debug:

    - name: Checking file differences
      ansible.builtin.command: diff file1 file2
      ignore_errors: yes

    - name: Last processing
      ansible.builtin.debug:
