---
- name: Example of error handling usage
  hosts: all

  tasks:
    - name: Install Apache only on CentOS
      ansible.builtin.dnf:
        name: httpd
        state: present
      become: yes
      when: ansible_facts['distribution'] == "CentOS"
      register: result_of_dnf

    - name: Display the contents of register variables
      ansible.builtin.debug:
        var: result_of_dnf
