---
- name: Example of error handling usage
  hosts: all
  gather_facts: no
 
  tasks:
    - name: Display the contents of the "/etc/passwd" file
      ansible.builtin.command: cat /etc/passwd
      changed_when: no
