---
- name: Example of error handling usage
  hosts: all

  tasks:
    - name: Copy the file
      ansible.builtin.copy:
        src: ~/textfile.txt
        dest: ~/file3
        mode: '0644'
      register: result_of_copy

    - name: Display the contents of register variables
      ansible.builtin.debug:
        var: result_of_copy
