---
- name: Example of error handling usage
  hosts: all
  gather_facts: no

  tasks:
    - name: First processing
      ansible.builtin.debug:

    - name: Checking file differences
      ansible.builtin.command: diff file1 file2
      register: result_of_diff
      failed_when:
        - result_of_diff['rc'] != 0
        - result_of_diff['rc'] != 1   

    - name: Last processing
      ansible.builtin.debug:
        var: result_of_diff
