---
- name: Example of loop usage
  hosts: hydrogen
  gather_facts: no

  tasks:
    - name: Get the date and time
      ansible.builtin.command: date
      register: result
      loop:
        - 1
        - 2
        - 3
      loop_control:
        pause: 10
    - name: Display the result
      ansible.builtin.debug:
        var: result
