# include/user-add.yml
---
- name: Create the specified user account when it has not yet been created.
  ansible.builtin.shell: "./user-add.sh {{ item }}"  
  register: user_status
  changed_when: user_status['rc'] == 1
  failed_when: user_status['rc'] > 1
