---
- name: Delegate the execution of a task
  hosts: web
  gather_facts: no

  tasks:
    - name: Get the hostname of a node
      ansible.builtin.command:
        cmd: hostname
      register: reg_hostname
      delegate_to: node1
    - name: Display the retrieved hostname
      ansible.builtin.debug:
        msg: "The hostname of the node is {{ reg_hostname['stdout'] }}."
