---
- name: Delegate the execution of a task
  hosts: web
  gather_facts: no

  tasks:
    - name: Get the hostname of a node
      local_action:
        module: ansible.builtin.command
        cmd: hostname
      register: reg_hostname
      delegate_to: localhost
    - name: Display the retrieved hostname
      ansible.builtin.debug:
        msg: "The hostname of the node is {{ reg_hostname['stdout'] }}."
