---
- name: Delegate the execution of a task
  hosts: web
  gather_facts: no

  tasks:
    - name: Get the name of the account that is logged into the node
      ansible.builtin.command:
        cmd: whoami
      register: reg_account
      delegate_to: beryllium.exam.local
    - name: Display the retrieved account name
      ansible.builtin.debug:
        msg: "The account name you are logged in as is {{ reg_account['stdout'] }}."
