---
- name: Example of a task variables
  hosts: webservers
  gather_facts: no

  tasks:
  - name: Install the latest version of the Apache package
    ansible.builtin.dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - httpd
        - httpd-tools
        - httpd-devel
        - httpd-manual
    become: yes
    