# imports/imp_task4.yml
---
- name: Register a user account.
  ansible.builtin.user:
    name: "hanako"
    state: present

- name: Install Apache
  ansible.builtin.dnf:
    name: httpd
    state: present
