---
- name: Example usage of the When directive
  hosts: all

  tasks:
    - name: Reboot a managed node on CentOS 8 or Ubuntu 20 or Debian 10
      ansible.builtin.reboot:
      when: ( ansible_facts['distribution'] == "CentOS" and 
              ansible_facts['distribution_major_version'] == "8" ) or
            ( ansible_facts['distribution'] == "Ubuntu" and 
              ansible_facts['distribution_major_version'] == "20" ) or
            ( ansible_facts['distribution'] == "Debian" and 
              ansible_facts['distribution_major_version'] == "10" )
      become: yes
