---
- name: Example usage of the When directive
  hosts: all

  tasks:
    - name: Reboot the managed nodes in the Debian family
      ansible.builtin.reboot:
      when: ansible_facts['os_family'] == "Debian"
      become: yes
