---
- name: Example usage of the When directive
  hosts: all

  tasks:
    - name: Reboot managed nodes with Debian, openSUSE Leap or Fedora distributions
      ansible.builtin.reboot:
      when: ansible_facts['distribution'] in distribution_list
      vars:
        distribution_list:
          - 'Debian'
          - 'openSUSE Leap'
          - 'Fedora'
      become: yes
